{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 12571,
          "sha512": "782bb5a565746304445f5232ccade2e176bf8454a2d02b96d51d3bd7e84798d8b3882746e803b5ea09407d22c41064a1fdea03f4016fddfe4e103560d16e8d74",
          "sha256": "c9253d2c822a9cc8a21b9d7e287ec82fa8765b01ac9afecf1bca0812891adacd",
          "sha1": "315950ebdc77d1464b86aa8e1bc77b95710726d7",
          "md5": "d278c45462516dbf1e42bf2b0c72b8f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 12571,
          "sha512": "782bb5a565746304445f5232ccade2e176bf8454a2d02b96d51d3bd7e84798d8b3882746e803b5ea09407d22c41064a1fdea03f4016fddfe4e103560d16e8d74",
          "sha256": "c9253d2c822a9cc8a21b9d7e287ec82fa8765b01ac9afecf1bca0812891adacd",
          "sha1": "315950ebdc77d1464b86aa8e1bc77b95710726d7",
          "md5": "d278c45462516dbf1e42bf2b0c72b8f3"
        }
      ]
    }
  ]
}
