{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "flutter_test",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_test-1.0.aar",
          "url": "flutter_test-1.0.aar",
          "size": 14397,
          "sha512": "b6f56a7e65fb693fbc59239a31576a0350315d147edf4c0b5e66e1d16e2ffaa387578d8770b0757e4993e45a3878a60ceb86cf33952effff2bcd792ffa3f08d9",
          "sha256": "ed20e6f91a9c5d3876884b5b2266f59fde2bda231d509d7aea44c1abcc2443eb",
          "sha1": "ddea06fee1297ad67f1d00e5769e3109347b278e",
          "md5": "dd624d3b356aeb9c9973874e3bd16013"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.example.modulefl",
          "module": "flutter_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_test-1.0.aar",
          "url": "flutter_test-1.0.aar",
          "size": 14397,
          "sha512": "b6f56a7e65fb693fbc59239a31576a0350315d147edf4c0b5e66e1d16e2ffaa387578d8770b0757e4993e45a3878a60ceb86cf33952effff2bcd792ffa3f08d9",
          "sha256": "ed20e6f91a9c5d3876884b5b2266f59fde2bda231d509d7aea44c1abcc2443eb",
          "sha1": "ddea06fee1297ad67f1d00e5769e3109347b278e",
          "md5": "dd624d3b356aeb9c9973874e3bd16013"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_test-1.0-sources.jar",
          "url": "flutter_test-1.0-sources.jar",
          "size": 4992,
          "sha512": "d9043e612bd744e40241bac706360c85c248987c4d75792fff302e03ee264843cd446396bc4526e48b03d5ad02213501d9912a72bd28495eb0658caff4a1e9ab",
          "sha256": "365e72e988284e411bd4dd1a85e02a885b525184be4be02e8e79a2f7ea5d84bc",
          "sha1": "c728e4e061c13426d7e0e3877e5c527c6f9c8a3c",
          "md5": "66280a709b1f696a7487b551f6643865"
        }
      ]
    }
  ]
}
